### ISSUE TITLE
Create South Korean site

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#807]
**As a South Korean user I would like to have a Korean site that has information about Equinors projects in the country**

## Acceptance criteria
1. Site to be served from equinor.kr **<To be verified>**
1. Site languages
  a. English
  b. Korean
1. Particular editors have access only to this site, and not to the rest of equinor.com

**<More info to be added>**

**Comment by meols** [comment]
@nilsml - we have gotten feedback from a stakeholder for the South Korea site, saying that they will launch this site  soon (before we close AEM), so we need this site to be created to be able to add content in Sanity as well.

**Comment by fernandolucchesi** [comment]
@padms, can you please add the cookie bot config for this new satellite?

https://studio-southkorea-energyvision-dev.radix.equinor.com/
https://web-southkorea-energyvision-dev.radix.equinor.com/

**Comment by padms** [comment]
Done!

**Comment by fernandolucchesi** [comment]
@meols

**Comment by meols** [comment]
@fernandolucchesi @padms  - looks good :smile: I'll confirm and close tomorrow, when I assume the cookie scanning is completed:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/0e95bb70-0da5-4972-bf04-e3dcf63d5490)

**Comment by meols** [comment]
@padms - this seems to still not be in place:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/8aabe001-d82f-4434-b67f-3d2edc2d35b1)
@fernandolucchesi

**Comment by meols** [comment]
@padms - I still see the same as above. Assume there is something wrong?
@fernandolucchesi

**Comment by padms** [comment]
@meols: Currently all the sites now mapped to their corresponding production sites, so all the cookies that are present in production are shown in the energyvision pages. Since South Korea site is not live in production, no cookies are found.

**Comment by meols** [comment]
Thanks for clarifying @padms - then I'll close this card
